package com.echoic.app

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf

data class Strings(
    // Sidebar
    val home: String,
    val cloudTts: String,
    val providers: String,
    val expandSidebar: String,
    val collapseSidebar: String,

    // Home Screen
    val welcome: String,
    val totalUsage: String,
    val totalCharacters: String,
    val mostUsedCloud: String,
    val mostUsedLocal: String,
    val startGenerating: String,
    val manageProviders: String,
    val manageLocalModels: String,
    val recentUsage: String,
    val quickActions: String,
    val runs: String,
    val chars: String,
    val noRecentUsage: String,

    // Cloud TTS Screen
    val textPlaceholder: String,
    val generate: String,
    val cancel: String,
    val settings: String,
    val newGeneration: String,
    val newGenerationDesc: String,
    val modelSelection: String,
    val filterTags: String,
    val voice: String,
    val ready: String,
    val needsConfig: String,
    val notSupported: String,
    val synthesizing: String,
    val generateSpeech: String,
    val charactersCount: String,
    val downloadCancelled: String,
    val modelNotSupported: String,
    val modelNotSupportedHint: String,
    val connectingDownload: String,

    // Settings
    val settingsTitle: String,
    val general: String,
    val appearance: String,
    val appearanceDesc: String,
    val language: String,
    val languageDesc: String,
    val light: String,
    val dark: String,
    val system: String,
    val aiProviders: String,
    val save: String,
    val version: String,

    // Config prompt
    val configRequired: String,
    val configRequiredDesc: String,
    val configure: String,
    val learnMore: String,
    val apiKeyRequired: String,
    val apiKeyRequiredDesc: String,
    val navigateToConfig: String,

    // Tag filter
    val filterByTags: String,
    val tagType: String,
    val tagTypeCloud: String,
    val tagTypeLocal: String,

    // Providers Screen
    val cloudModels: String,
    val localModels: String,
    val cloudServices: String,
    val cloudServicesDesc: String,
    val localModelsDesc: String,
    val comingSoon: String,
    val availableModels: String,
    val availableVoices: String,
    val clickToExpand: String,
    val noProvidersMatch: String,

    // API Key Configuration
    val getApiKey: String,
    val saveConfig: String,
    val apiKey: String,
    val baseUrl: String,

    // Website
    val visitWebsite: String,

    // Local Models Screen
    val downloadFirst: String,
    val install: String,
    val uninstall: String,
    val clearCache: String,
    val openDirectory: String,
    val installed: String,
    val notInstalled: String,
    val modelSize: String,
    val lastUsed: String,
    val clearAll: String,
    val checkUpdates: String,
    val platformSupport: String,
    val modelDescription: String,
    val installing: String,
    val error: String,
    val dismiss: String,
    val localSynthesisFailed: String,

    // Local Model Links
    val downloadModel: String,
    val viewOnGitHub: String,
    val viewDocumentation: String,

    // Generate Screen
    val generateSpeechTitle: String,
    val generateSpeechDesc: String,
    val synthesisMode: String,
    val defaultModel: String,
    val setAsDefault: String,
    val isDefault: String,
    val noDefaultCloud: String,
    val noDefaultLocal: String,
    val goToProviders: String,
    val goToLocalModels: String,
    val selectDefaultFirst: String,
    val cloud: String,
    val local: String,
    val playing: String,
    val playbackStopped: String,

    // Download
    val downloading: String,
    val downloadComplete: String,
    val downloadFailed: String,
    val selectSource: String,
    val autoSelect: String,
    val switchSource: String,
    val recommended: String,
    val speed: String,
    val priority: String,

    // Installer
    val extracting: String,
    val verifying: String,
    val installComplete: String,
    val installFailed: String,
    val retryInstall: String,
    val selectOtherSource: String,
    val modelAlreadyInstalled: String,

    // Multi-file download
    val downloadingMultiple: String,
)

val EnglishStrings = Strings(
    home = "Home",
    cloudTts = "Cloud TTS",
    providers = "Providers",
    expandSidebar = "Expand",
    collapseSidebar = "Collapse",
    welcome = "Welcome to Echoic",
    totalUsage = "Total Usage",
    totalCharacters = "Total Characters",
    mostUsedCloud = "Most Used Cloud",
    mostUsedLocal = "Most Used Local",
    startGenerating = "Start Generating",
    manageProviders = "Manage Providers",
    manageLocalModels = "Manage Local Models",
    recentUsage = "Recent Usage",
    quickActions = "Quick Actions",
    runs = "Runs",
    chars = "Chars",
    noRecentUsage = "No recent usage yet",
    textPlaceholder = "Enter text to synthesize...",
    generate = "Generate",
    cancel = "Cancel",
    settings = "Settings",
    newGeneration = "New Generation",
    newGenerationDesc = "Create ultra-realistic speech from text",
    modelSelection = "Model",
    filterTags = "Filter Tags",
    voice = "Voice",
    ready = "Ready",
    needsConfig = "Needs Config",
    notSupported = "N/A",
    synthesizing = "Synthesizing...",
    generateSpeech = ">> Generate",
    charactersCount = "%d / 5000 characters",
    downloadCancelled = "Download cancelled — retry",
    modelNotSupported = "Model not supported for local synthesis",
    modelNotSupportedHint = "Use Sherpa-ONNX VITS models for best compatibility",
    connectingDownload = "Connecting to download source...",
    settingsTitle = "Settings",
    general = "GENERAL",
    appearance = "Appearance",
    appearanceDesc = "Interface theme",
    language = "Language",
    languageDesc = "System language",
    light = "Light",
    dark = "Dark",
    system = "System",
    aiProviders = "AI PROVIDERS",
    save = "Save",
    version = "Echoic v1.0.0",
    configRequired = "Not Available",
    configRequiredDesc = "Please configure your API key in Providers to use this provider.",
    configure = "Configure in Providers",
    learnMore = "Learn More",
    apiKeyRequired = "API Key Required",
    apiKeyRequiredDesc = "To use %s speech synthesis service, please configure your API key first. Click the button below to go to the configuration page.",
    navigateToConfig = "Go to Provider Config",
    filterByTags = "Filter by tags",
    tagType = "Type",
    tagTypeCloud = "Cloud",
    tagTypeLocal = "Local",
    cloudModels = "Cloud Models",
    localModels = "Local Models",
    cloudServices = "Cloud Services",
    cloudServicesDesc = "Use cloud APIs for speech synthesis",
    localModelsDesc = "Run models on local device",
    comingSoon = "Coming Soon",
    availableModels = "Available Models",
    availableVoices = "Available Voices",
    clickToExpand = "Click to expand",
    noProvidersMatch = "No providers match the selected tags",
    getApiKey = "Get API Key",
    saveConfig = "Save Configuration",
    apiKey = "API Key",
    baseUrl = "Base URL (optional)",
    visitWebsite = "Visit Website",
    downloadFirst = "Download model first",
    install = "Install",
    uninstall = "Uninstall",
    clearCache = "Clear Cache",
    openDirectory = "Open Directory",
    installed = "Installed",
    notInstalled = "Not Installed",
    modelSize = "Model Size",
    lastUsed = "Last Used",
    clearAll = "Clear All",
    checkUpdates = "Check Updates",
    platformSupport = "Platform Support",
    modelDescription = "Description",
    installing = "Installing...",
    error = "Error",
    dismiss = "Dismiss",
    localSynthesisFailed = "Local synthesis failed",
    downloadModel = "Download Model",
    viewOnGitHub = "View on GitHub",
    viewDocumentation = "View Documentation",
    generateSpeechTitle = "Generate Speech",
    generateSpeechDesc = "Create speech from text using your default models",
    synthesisMode = "Mode",
    defaultModel = "Default Model",
    setAsDefault = "Set as Default",
    isDefault = "Default",
    noDefaultCloud = "No default cloud model set",
    noDefaultLocal = "No default local model set",
    goToProviders = "Configure in Providers",
    goToLocalModels = "Manage Local Models",
    selectDefaultFirst = "Please set a default model first",
    cloud = "Cloud",
    local = "Local",
    playing = "Playing...",
    playbackStopped = "Playback stopped",
    downloading = "Downloading",
    downloadComplete = "Download Complete",
    downloadFailed = "Download Failed",
    selectSource = "Select Download Source",
    autoSelect = "Auto Select Best",
    switchSource = "Switch Source",
    recommended = "Recommended",
    speed = "Speed",
    priority = "Priority",
    extracting = "Extracting...",
    verifying = "Verifying...",
    installComplete = "Installation Complete",
    installFailed = "Installation Failed",
    retryInstall = "Retry Install",
    selectOtherSource = "Select Other Source",
    modelAlreadyInstalled = "Model Already Installed",
    downloadingMultiple = "Downloading (%d/%d)",
)

val ChineseStrings = Strings(
    home = "首页",
    cloudTts = "云端 TTS",
    providers = "服务商",
    expandSidebar = "展开",
    collapseSidebar = "收起",
    welcome = "欢迎使用 Echoic",
    totalUsage = "总使用次数",
    totalCharacters = "总字符数",
    mostUsedCloud = "最常用云端服务商",
    mostUsedLocal = "最常用本地模型",
    startGenerating = "开始生成语音",
    manageProviders = "管理服务商",
    manageLocalModels = "管理本地模型",
    recentUsage = "最近使用",
    quickActions = "快捷操作",
    runs = "次",
    chars = "字符",
    noRecentUsage = "暂无使用记录",
    textPlaceholder = "输入要合成的文本...",
    generate = "生成",
    cancel = "取消",
    settings = "设置",
    newGeneration = "新建合成",
    newGenerationDesc = "将文本转换为逼真的语音",
    modelSelection = "选择模型",
    filterTags = "标签筛选",
    voice = "语音",
    ready = "就绪",
    needsConfig = "需配置",
    notSupported = "不支持",
    synthesizing = "合成中...",
    generateSpeech = ">> 生成语音",
    charactersCount = "%d / 5000 字符",
    downloadCancelled = "下载已取消 — 可重试",
    modelNotSupported = "该模型暂不支持本地合成",
    modelNotSupportedHint = "请使用 Sherpa-ONNX VITS 模型以获得最佳兼容性",
    connectingDownload = "正在连接下载源...",
    settingsTitle = "设置",
    general = "通用",
    appearance = "外观",
    appearanceDesc = "界面主题",
    language = "语言",
    languageDesc = "系统语言",
    light = "浅色",
    dark = "深色",
    system = "跟随系统",
    aiProviders = "AI 服务商",
    save = "保存",
    version = "Echoic v1.0.0",
    configRequired = "暂不可用",
    configRequiredDesc = "请在服务商页面配置 API Key 以使用此服务商。",
    configure = "前往服务商配置",
    learnMore = "了解更多",
    apiKeyRequired = "需要配置 API Key",
    apiKeyRequiredDesc = "要使用 %s 的语音合成服务，请先配置 API Key。点击下方按钮前往配置页面。",
    navigateToConfig = "前往服务商配置",
    filterByTags = "按标签筛选",
    tagType = "类型",
    tagTypeCloud = "云端",
    tagTypeLocal = "本地",
    cloudModels = "云端模型",
    localModels = "本地模型",
    cloudServices = "云端服务",
    cloudServicesDesc = "使用云端 API 进行语音合成",
    localModelsDesc = "在本地设备上运行模型",
    comingSoon = "即将推出",
    availableModels = "可用模型",
    availableVoices = "可用语音",
    clickToExpand = "点击展开",
    noProvidersMatch = "没有匹配所选标签的服务商",
    getApiKey = "获取 API Key",
    saveConfig = "保存配置",
    apiKey = "API Key",
    baseUrl = "Base URL (可选)",
    visitWebsite = "访问官网",
    downloadFirst = "请先下载模型",
    install = "安装",
    uninstall = "卸载",
    clearCache = "清除缓存",
    openDirectory = "打开目录",
    installed = "已安装",
    notInstalled = "未安装",
    modelSize = "模型大小",
    lastUsed = "最后使用",
    clearAll = "全部清除",
    checkUpdates = "检查更新",
    platformSupport = "平台支持",
    modelDescription = "描述",
    installing = "安装中...",
    error = "错误",
    dismiss = "关闭",
    localSynthesisFailed = "本地合成失败",
    downloadModel = "下载模型",
    viewOnGitHub = "查看 GitHub",
    viewDocumentation = "查看文档",
    generateSpeechTitle = "生成语音",
    generateSpeechDesc = "使用预设默认模型进行语音合成",
    synthesisMode = "合成方式",
    defaultModel = "默认模型",
    setAsDefault = "设为默认",
    isDefault = "默认",
    noDefaultCloud = "未设置默认云端模型",
    noDefaultLocal = "未设置默认本地模型",
    goToProviders = "前往服务商配置",
    goToLocalModels = "管理本地模型",
    selectDefaultFirst = "请先在服务商或本地模型中选择默认模型",
    cloud = "云端",
    local = "本地",
    playing = "播放中...",
    playbackStopped = "播放已停止",
    downloading = "下载中",
    downloadComplete = "下载完成",
    downloadFailed = "下载失败",
    selectSource = "选择下载源",
    autoSelect = "自动选择最佳",
    switchSource = "切换下载源",
    recommended = "推荐",
    speed = "速度",
    priority = "优先级",
    extracting = "解压中...",
    verifying = "验证中...",
    installComplete = "安装完成",
    installFailed = "安装失败",
    retryInstall = "重新安装",
    selectOtherSource = "选择其他线路",
    modelAlreadyInstalled = "模型已安装",
    downloadingMultiple = "下载中 (%d/%d)",
)

val LocalStrings = staticCompositionLocalOf { EnglishStrings }

fun stringsFor(language: String): Strings = when (language) {
    "zh" -> ChineseStrings
    else -> EnglishStrings
}
